; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 < %s | FileCheck %s

define i128 @udiv_i128(i128 %x, i128 %y) nounwind {
  %res = udiv i128 %x, %y
  ret i128 %res
}

define i129 @udiv_i129(i129 %x, i129 %y) nounwind {
  %res = udiv i129 %x, %y
  ret i129 %res
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
