# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -run-pass=aarch64-mi-peephole-opt -o - -mtriple=aarch64-unknown-linux -verify-machineinstrs %s | FileCheck %s

---
name: transform_lsr_and_ldr_to_lsr_ldr2
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x0, $x1, $x2
    ; CHECK-LABEL: name: transform_lsr_and_ldr_to_lsr_ldr2
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64 = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr64 = COPY $x0
    ; CHECK-NEXT: [[MADDXrrr:%[0-9]+]]:gpr64 = MADDXrrr [[COPY1]], [[COPY2]], $xzr
    ; CHECK-NEXT: [[UBFMXri:%[0-9]+]]:gpr64 = UBFMXri killed [[MADDXrrr]], 58, 63
    ; CHECK-NEXT: [[LDRWroX:%[0-9]+]]:gpr32 = LDRWroX [[COPY]], killed [[UBFMXri]], 0, 1
    ; CHECK-NEXT: $w0 = COPY [[LDRWroX]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %2:gpr64common = COPY $x2
    %1:gpr64 = COPY $x1
    %0:gpr64 = COPY $x0
    %3:gpr64 = MADDXrrr %1, %0, $xzr
    %4:gpr64 = UBFMXri killed %3, 56, 63
    %5:gpr64common = ANDXri killed %4, 8069
    %6:gpr32 = LDRWroX %2, killed %5, 0, 0
    $w0 = COPY %6
    RET_ReallyLR implicit $w0
...
---
name: transform_lsl1_and_ldr_to_lsr1_ldr2
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x0, $x1, $x2
    ; CHECK-LABEL: name: transform_lsl1_and_ldr_to_lsr1_ldr2
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64 = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr64 = COPY $x0
    ; CHECK-NEXT: [[MADDXrrr:%[0-9]+]]:gpr64 = MADDXrrr [[COPY1]], [[COPY2]], $xzr
    ; CHECK-NEXT: [[UBFMXri:%[0-9]+]]:gpr64 = UBFMXri killed [[MADDXrrr]], 1, 63
    ; CHECK-NEXT: [[LDRWroX:%[0-9]+]]:gpr32 = LDRWroX [[COPY]], killed [[UBFMXri]], 0, 1
    ; CHECK-NEXT: $w0 = COPY [[LDRWroX]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %2:gpr64common = COPY $x2
    %1:gpr64 = COPY $x1
    %0:gpr64 = COPY $x0
    %3:gpr64 = MADDXrrr %1, %0, $xzr
    %4:gpr64 = UBFMXri killed %3, 63, 62
    %5:gpr64common = ANDXri killed %4, 8125
    %6:gpr32 = LDRWroX %2, killed %5, 0, 0
    $w0 = COPY %6
    RET_ReallyLR implicit $w0
...
---
name: donot_transform_and_ldr
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x0, $x1, $x2
    ; CHECK-LABEL: name: donot_transform_and_ldr
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64 = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr64 = COPY $x0
    ; CHECK-NEXT: [[MADDXrrr:%[0-9]+]]:gpr64 = MADDXrrr [[COPY1]], [[COPY2]], $xzr
    ; CHECK-NEXT: [[ANDXri:%[0-9]+]]:gpr64common = ANDXri killed [[MADDXrrr]], 8125
    ; CHECK-NEXT: [[LDRWroX:%[0-9]+]]:gpr32 = LDRWroX [[COPY]], killed [[ANDXri]], 0, 0
    ; CHECK-NEXT: $w0 = COPY [[LDRWroX]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %2:gpr64common = COPY $x2
    %1:gpr64 = COPY $x1
    %0:gpr64 = COPY $x0
    %3:gpr64 = MADDXrrr %1, %0, $xzr
    %4:gpr64common = ANDXri killed %3, 8125
    %5:gpr32 = LDRWroX %2, killed %4, 0, 0
    $w0 = COPY %5
    RET_ReallyLR implicit $w0
...
---
name: donot_transform_if_not_lsl
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x0, $x1, $x2
    ; CHECK-LABEL: name: donot_transform_if_not_lsl
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64 = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr64 = COPY $x0
    ; CHECK-NEXT: [[MADDXrrr:%[0-9]+]]:gpr64 = MADDXrrr [[COPY1]], [[COPY2]], $xzr
    ; CHECK-NEXT: [[UBFMXri:%[0-9]+]]:gpr64 = UBFMXri killed [[MADDXrrr]], 64, 62
    ; CHECK-NEXT: [[ANDXri:%[0-9]+]]:gpr64common = ANDXri killed [[UBFMXri]], 8125
    ; CHECK-NEXT: [[LDRWroX:%[0-9]+]]:gpr32 = LDRWroX [[COPY]], killed [[ANDXri]], 0, 0
    ; CHECK-NEXT: $w0 = COPY [[LDRWroX]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %2:gpr64common = COPY $x2
    %1:gpr64 = COPY $x1
    %0:gpr64 = COPY $x0
    %3:gpr64 = MADDXrrr %1, %0, $xzr
    %4:gpr64 = UBFMXri killed %3, 64, 62
    %5:gpr64common = ANDXri killed %4, 8125
    %6:gpr32 = LDRWroX %2, killed %5, 0, 0
    $w0 = COPY %6
    RET_ReallyLR implicit $w0
...
---
name: donot_transform_if_not_lsr
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x0, $x1, $x2
    ; CHECK-LABEL: name: donot_transform_if_not_lsr
    ; CHECK: liveins: $x0, $x1, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64 = COPY $x1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr64 = COPY $x0
    ; CHECK-NEXT: [[MADDXrrr:%[0-9]+]]:gpr64 = MADDXrrr [[COPY1]], [[COPY2]], $xzr
    ; CHECK-NEXT: [[UBFMXri:%[0-9]+]]:gpr64 = UBFMXri killed [[MADDXrrr]], 62, 62
    ; CHECK-NEXT: [[ANDXri:%[0-9]+]]:gpr64common = ANDXri killed [[UBFMXri]], 8069
    ; CHECK-NEXT: [[LDRWroX:%[0-9]+]]:gpr32 = LDRWroX [[COPY]], killed [[ANDXri]], 0, 0
    ; CHECK-NEXT: $w0 = COPY [[LDRWroX]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %2:gpr64common = COPY $x2
    %1:gpr64 = COPY $x1
    %0:gpr64 = COPY $x0
    %3:gpr64 = MADDXrrr %1, %0, $xzr
    %4:gpr64 = UBFMXri killed %3, 62, 62
    %5:gpr64common = ANDXri killed %4, 8069
    %6:gpr32 = LDRWroX %2, killed %5, 0, 0
    $w0 = COPY %6
    RET_ReallyLR implicit $w0
...
---
name: donot_transform_if_not_exist_and_and_lsl
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x0, $x2
    ; CHECK-LABEL: name: donot_transform_if_not_exist_and_and_lsl
    ; CHECK: liveins: $x0, $x2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr64common = COPY $x2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr64 = COPY $x0
    ; CHECK-NEXT: [[UBFMXri:%[0-9]+]]:gpr64 = UBFMXri [[COPY1]], 61, 60
    ; CHECK-NEXT: [[LDRWroX:%[0-9]+]]:gpr32 = LDRWroX [[COPY]], killed [[UBFMXri]], 0, 0
    ; CHECK-NEXT: $w0 = COPY [[LDRWroX]]
    ; CHECK-NEXT: RET_ReallyLR implicit $w0
    %2:gpr64common = COPY $x2
    %0:gpr64 = COPY $x0
    %3:gpr64 = UBFMXri %0, 61, 60
    %4:gpr32 = LDRWroX %2, killed %3, 0, 0
    $w0 = COPY %4
    RET_ReallyLR implicit $w0
