name: "Windows Precommit Tests"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build-llvm-windows:
    name: "Build and test LLVM (Windows)"
    runs-on: windows-2022
    steps:
      - name: Setup Windows
        uses: llvm/actions/setup-windows@main
        with:
          arch: amd64
      - name: Fetch LLVM sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 500M
          variant: sccache
          key: precommit-windows
      - name: Compute projects to test
        id: compute-projects
        uses: ./.github/workflows/compute-projects-to-test

      - name: Configure LLVM
        shell: bash
        if: ${{ steps.compute-projects.outputs.check-targets }}
        run: |
          cmake -B build -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="${{ steps.compute-projects.outputs.projects }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=sccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_LIT_ARGS="-v --no-progress-bar" \
            -S llvm
      - name: Check LLVM
        if: ${{ steps.compute-projects.outputs.check-targets }}
        run: |
          ninja -C build ${{ steps.compute-projects.outputs.check-targets }}
